// -*- C++ -*- generated by wxGlade 0.3.5.1 on Fri Mar 18 17:43:25 2005
#ifndef MAINFRAME_H
#define MAINFRAME_H
#include "wxprec.h"
#include "TrackRunner.h"
#include "OptionPane.h"
#include "GLView.h"
#include "AlgosPanel.h"
#include "Observer.h"

class MainFrame: public wxFrame, public Observer
{
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	~MainFrame();
	/**
	 * Update all sliders in option tabs.
	 */
	void UpdatePanes();
	virtual void Update(Observable *observable);
protected:
	enum
	{
		wxID_CAM1PROP = 1,
		wxID_CAM2PROP,
		wxID_RES,
		wxID_OPTIONS,
		wxID_LOAD,
		wxID_SAVE,
		wxID_CALIB,
		wxID_LOG,
		wxID_LOGTEXT
	};
private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade
	void InitTracker();
	void OnOptionsToggle(wxCommandEvent& event);
	void OnCalibrate(wxCommandEvent& event);
	void OnExit(wxCommandEvent& event);
	void OnCam1Prop(wxCommandEvent& event);
	void OnCam2Prop(wxCommandEvent& event);
	void OnRes(wxCommandEvent& event);
	void OnLoad(wxCommandEvent& event);
	void OnSave(wxCommandEvent& event);
	void OnClose(wxCloseEvent& event);
	void OnPrefsToggle(wxCommandEvent& event);
	void OnLogToggle(wxCommandEvent& event);
	void OnGLChanged(wxCommandEvent& event);
	void OnFPS(wxCommandEvent& event);
	void OnShow(wxShowEvent& event);

	void UpdateCameraWindows();
	void UpdateLayout();
protected:
    // begin wxGlade: MainFrame::attributes
    wxMenuBar* m_menubar;
    wxStatusBar* m_statusbar;
    wxToolBar* m_mainToolbar;
    wxPanel* m_mainPanel;
    wxPanel* m_leftCameraView;
    wxPanel* m_rightCameraView;
	wxNotebook* m_prefs;
	wxNotebook* m_options;
	AlgosPanel* m_algosPanel;

	wxBoxSizer* m_frameSizer;
	wxBoxSizer* m_middleSizer;
	wxBoxSizer* m_camWindowsSizer;
	wxBoxSizer* m_buttonsPanelSizer;
	wxBoxSizer* m_trackResultsSizer;
	wxBoxSizer* m_mainSizer;
	wxTextCtrl* m_fpsTextCtrl;
	wxTextCtrl* m_pos3dTextCtrl;
	GLView* m_glCanvas;
    wxToggleButton* m_tglbtnOptions;
	wxButton* m_btnCalibrate;

    // end wxGlade

	TrackRunner * m_pTrackRunner;

//	WX_DECLARE_ARRAY(OptionPane*, ArrayOfPanes);
	WX_DEFINE_ARRAY_PTR(OptionPane*, ArrayOfPanes);

	ArrayOfPanes m_panes;
	DECLARE_EVENT_TABLE();
};

#endif // MAINFRAME_H
